import type { AppProps } from 'next/app';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/system';
import { RecoilRoot } from 'recoil';
import DebugObserver from '../lib/DebugObserver';
import Layout from '../components/layout/Layout';
import theme from '../lib/theme';
import Head from 'next/head';

const isDev = process.env.NODE_ENV === 'development';

if (process.env.NEXT_PUBLIC_API_MOCKING === 'enabled') {
  require('../mocks');
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <RecoilRoot>
      {isDev && <DebugObserver />}
      <ThemeProvider theme={theme}>
        <Head>
          <title>My Resume Builder</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <CssBaseline />
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </RecoilRoot>
  );
}

export default MyApp;
