import type { AppProps } from 'next/app';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/system';
import { SessionProvider } from 'next-auth/react';
import { RecoilRoot } from 'recoil';
import DebugObserver from '../lib/DebugObserver';
import Layout from '../components/layout/Layout';
import theme from '../lib/theme';
import Head from 'next/head';
import React from 'react';

const isDev = process.env.NODE_ENV === 'development';

if (process.env.NEXT_PUBLIC_API_MOCKING === 'enabled') {
  const MockServer = () => import('@/mokcs/worker');
  MockServer();
}

function MyApp({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  return (
    <SessionProvider session={session}>
      <RecoilRoot>
        {isDev && <DebugObserver />}
        <ThemeProvider theme={theme}>
          <Head>
            <title>My Resume Builder</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <CssBaseline />
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </ThemeProvider>
      </RecoilRoot>
    </SessionProvider>
  );
}

export default MyApp;
