import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button variant="contained">Hello World</Button>
    </div>
  );
};

export default Home;
