name: deploy

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: yarn install
      - name: build storybook
        run: yarn build-storybook
      - name: deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: $${github.event.pull_request.number}
          body: |
            Storybook をデプロイしました。
            - https://azukiazusa1.github.io/my-resume-builder/
          reactions: 'eyes'
