name: storybook

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Preview-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Enable node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Build storybook
        run: yarn build-storybook -o ./dist/storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Create comments
        run: |
          echo "1st" >> comments
          echo "2nd" >> comments
          echo "${{ env.GITHUB_REPOSITORY }}" >> comments
